---
- hosts: all
  gather_facts: yes
  become: true
  roles:
    - { role: opsta.erlang, when: sensu_all_in_one | default(false) }
    - { role: opsta.rabbitmq, when: sensu_all_in_one | default(false) }
    - { role: opsta.redis, when: sensu_all_in_one | default(false) }
    - opsta.sensu
