---
- hosts: all
  gather_facts: yes
  become: true
  roles:
    - opsta.java
    - { role: opsta.zookeeper, when: use_zookeeper_role | default(false) }
    - opsta.kafka
  environment: "{{ proxy_env | default({}) }}"
