---
- hosts: all
  gather_facts: yes
  become: true
  roles:
    - { role: opsta.postgresql, when: sonarqube_all_in_one | default(true) }
    - opsta.java
    - opsta.sonarqube
  environment: "{{ proxy_env | default({}) }}"
